// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026. 1. 16. AM 8:35:02
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/plugins/**/*.{js,ts,mjs}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/composables/**/*.{js,ts,mjs}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/utils/**/*.{js,ts,mjs}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/leemyeongseok/Documents/alimi-phase6-detail-page/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;